"""Adding remember hashes

Revision ID: a48fd13c6d26
Revises: 197b0a27c798
Create Date: 2021-05-04 08:52:53.510260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48fd13c6d26'
down_revision = '197b0a27c798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remember_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remembers_user_id'), 'remembers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remembers_user_id'), table_name='remembers')
    op.drop_table('remembers')
    # ### end Alembic commands ###
